export const geoApiMocks = {
    COMMUNITY: {
        CCOM: '05',
        COM: 'CANARIAS',
    },

    PROVINCES: [
        {
            CCOM: '05',
            CPRO: '35',
            PRO: 'LAS PALMAS',
        },
        {
            CCOM: '05',
            CPRO: '38',
            PRO: 'SANTA CRUZ DE TENERIFE',
        },
    ],
    MUNICIPALITY: {
        LASPALMAS: [
            {
                CMUM: '001',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'AGAETE',
            },
            {
                CMUM: '002',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'AGÜIMES',
            },
            {
                CMUM: '020',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'ALDEA DE SAN NICOLÁS (LA)',
            },
            {
                CMUM: '003',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'ANTIGUA',
            },
            {
                CMUM: '004',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'ARRECIFE',
            },
            {
                CMUM: '005',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'ARTENARA',
            },
            {
                CMUM: '006',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'ARUCAS',
            },
            {
                CMUM: '007',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'BETANCURIA',
            },
            {
                CMUM: '008',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'FIRGAS',
            },
            {
                CMUM: '009',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'GÁLDAR',
            },
            {
                CMUM: '010',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'HARÍA',
            },
            {
                CMUM: '011',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'INGENIO',
            },
            {
                CMUM: '012',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'MOGÁN',
            },
            {
                CMUM: '013',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'MOYA',
            },
            {
                CMUM: '014',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'OLIVA (LA)',
            },
            {
                CMUM: '015',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'PÁJARA',
            },
            {
                CMUM: '016',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'PALMAS DE GRAN CANARIA (LAS)',
            },
            {
                CMUM: '017',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'PUERTO DEL ROSARIO',
            },
            {
                CMUM: '018',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'SAN BARTOLOMÉ',
            },
            {
                CMUM: '019',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'SAN BARTOLOMÉ DE TIRAJANA',
            },
            {
                CMUM: '021',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'SANTA BRÍGIDA',
            },
            {
                CMUM: '022',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'SANTA LUCÍA DE TIRAJANA',
            },
            {
                CMUM: '023',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'SANTA MARÍA DE GUÍA DE GRAN CANARIA',
            },
            {
                CMUM: '024',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'TEGUISE',
            },
            {
                CMUM: '025',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'TEJEDA',
            },
            {
                CMUM: '026',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'TELDE',
            },
            {
                CMUM: '027',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'TEROR',
            },
            {
                CMUM: '028',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'TÍAS',
            },
            {
                CMUM: '029',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'TINAJO',
            },
            {
                CMUM: '030',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'TUINEJE',
            },
            {
                CMUM: '032',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'VALLESECO',
            },
            {
                CMUM: '031',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'VALSEQUILLO DE GRAN CANARIA',
            },
            {
                CMUM: '033',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'VEGA DE SAN MATEO',
            },
            {
                CMUM: '034',
                CPRO: '35',
                CUN: '0000000',
                DMUN50: 'YAIZA',
            },
        ],
        TENERIFE: [
            {
                CMUM: '001',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'ADEJE',
            },
            {
                CMUM: '002',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'AGULO',
            },
            {
                CMUM: '003',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'ALAJERÓ',
            },
            {
                CMUM: '004',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'ARAFO',
            },
            {
                CMUM: '005',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'ARICO',
            },
            {
                CMUM: '006',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'ARONA',
            },
            {
                CMUM: '007',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'BARLOVENTO',
            },
            {
                CMUM: '008',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'BREÑA ALTA',
            },
            {
                CMUM: '009',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'BREÑA BAJA',
            },
            {
                CMUM: '010',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'BUENAVISTA DEL NORTE',
            },
            {
                CMUM: '011',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'CANDELARIA',
            },
            {
                CMUM: '012',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'FASNIA',
            },
            {
                CMUM: '013',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'FRONTERA',
            },
            {
                CMUM: '014',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'FUENCALIENTE DE LA PALMA',
            },
            {
                CMUM: '015',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'GARACHICO',
            },
            {
                CMUM: '016',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'GARAFÍA',
            },
            {
                CMUM: '017',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'GRANADILLA DE ABONA',
            },
            {
                CMUM: '018',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'GUANCHA (LA)',
            },
            {
                CMUM: '019',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'GUÍA DE ISORA',
            },
            {
                CMUM: '020',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'GÜÍMAR',
            },
            {
                CMUM: '021',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'HERMIGUA',
            },
            {
                CMUM: '022',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'ICOD DE LOS VINOS',
            },
            {
                CMUM: '024',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'LLANOS DE ARIDANE (LOS)',
            },
            {
                CMUM: '025',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'MATANZA DE ACENTEJO (LA)',
            },
            {
                CMUM: '026',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'OROTAVA (LA)',
            },
            {
                CMUM: '027',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'PASO (EL)',
            },
            {
                CMUM: '901',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'PINAR DE EL HIERRO (EL)',
            },
            {
                CMUM: '028',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'PUERTO DE LA CRUZ',
            },
            {
                CMUM: '029',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'PUNTAGORDA',
            },
            {
                CMUM: '030',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'PUNTALLANA',
            },
            {
                CMUM: '031',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'REALEJOS (LOS)',
            },
            {
                CMUM: '032',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'ROSARIO (EL)',
            },
            {
                CMUM: '033',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'SAN ANDRÉS Y SAUCES',
            },
            {
                CMUM: '023',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'SAN CRISTÓBAL DE LA LAGUNA',
            },
            {
                CMUM: '034',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'SAN JUAN DE LA RAMBLA',
            },
            {
                CMUM: '035',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'SAN MIGUEL DE ABONA',
            },
            {
                CMUM: '036',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'SAN SEBASTIÁN DE LA GOMERA',
            },
            {
                CMUM: '037',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'SANTA CRUZ DE LA PALMA',
            },
            {
                CMUM: '038',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'SANTA CRUZ DE TENERIFE',
            },
            {
                CMUM: '039',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'SANTA ÚRSULA',
            },
            {
                CMUM: '040',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'SANTIAGO DEL TEIDE',
            },
            {
                CMUM: '041',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'SAUZAL (EL)',
            },
            {
                CMUM: '042',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'SILOS (LOS)',
            },
            {
                CMUM: '043',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'TACORONTE',
            },
            {
                CMUM: '044',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'TANQUE (EL)',
            },
            {
                CMUM: '045',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'TAZACORTE',
            },
            {
                CMUM: '046',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'TEGUESTE',
            },
            {
                CMUM: '047',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'TIJARAFE',
            },
            {
                CMUM: '049',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'VALLE GRAN REY',
            },
            {
                CMUM: '050',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'VALLEHERMOSO',
            },
            {
                CMUM: '048',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'VALVERDE',
            },
            {
                CMUM: '051',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'VICTORIA DE ACENTEJO (LA)',
            },
            {
                CMUM: '052',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'VILAFLOR DE CHASNA',
            },
            {
                CMUM: '053',
                CPRO: '38',
                CUN: '0000000',
                DMUN50: 'VILLA DE MAZO',
            },
        ],
    },
    POPULATION: [
        {
            CPRO: '35',
            CMUM: '002',
            CUN: '0001701',
            NENTSI50: 'AGÜIMES',
        },
        {
            CPRO: '35',
            CMUM: '002',
            CUN: '0003801',
            NENTSI50: 'BANDA (LA)',
        },
        {
            CPRO: '35',
            CMUM: '002',
            CUN: '0004301',
            NENTSI50: 'CORRALILLOS LOS',
        },
        {
            CPRO: '35',
            CMUM: '002',
            CUN: '0005601',
            NENTSI50: 'CRUCE DE ARINAGA',
        },
        {
            CPRO: '35',
            CMUM: '002',
            CUN: '0012001',
            NENTSI50: 'CUARTERIA EL UNO',
        },
        {
            CPRO: '35',
            CMUM: '002',
            CUN: '0006901',
            NENTSI50: 'GOLETA (LA)',
        },
        {
            CPRO: '35',
            CMUM: '002',
            CUN: '0019201',
            NENTSI50: 'MONTAÑA LOS VELEZ',
        },
        {
            CPRO: '35',
            CMUM: '002',
            CUN: '0018901',
            NENTSI50: 'MONTAÑA SAN FRANCISCO',
        },
        {
            CPRO: '35',
            CMUM: '002',
            CUN: '0002201',
            NENTSI50: 'PLAYA DE ARINAGA',
        },
        {
            CPRO: '35',
            CMUM: '002',
            CUN: '0023402',
            NENTSI50: 'POLIGONO DE ARINAGA',
        },
        {
            CPRO: '35',
            CMUM: '002',
            CUN: '0007501',
            NENTSI50: 'ROSAS (LAS)',
        },
        {
            CPRO: '35',
            CMUM: '002',
            CUN: '0008101',
            NENTSI50: 'TEMISAS',
        },
        {
            CPRO: '35',
            CMUM: '002',
            CUN: '0009401',
            NENTSI50: 'VARGAS',
        },
    ],
};
